name: "Build and deploy to dev"

on: [workflow_dispatch]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    outputs:
      upload_url: ${{ steps.export-cdn-url.outputs.url }}
    steps:
      - uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" # ratchet:actions/checkout@v4
      - uses: "actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020" # ratchet:actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"
      - name: "Install dependencies"
        run: "npm ci"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: "Build application"
        run: "npm run build"
      - name: cdn-upload
        uses: nais/deploy/actions/cdn-upload/v2@655191e618af58744d594ab4226aeac78dc739ec # ratchet:nais/deploy/actions/cdn-upload/v2@master
        with:
          team: teamfamilie
          source: ./dist/
          destination: "familie-ef-mikrofrontend-minside"
      - name: export-cdn-url
        id: export-cdn-url
        run: |
          paths="${{ steps.cdn-upload.outputs.uploaded }}"
          cdn_js_path=$(echo $paths | cut -d',' -f1)
          echo "url=https://cdn.nav.no/$cdn_js_path" >> $GITHUB_OUTPUT
  manifest-update-dev:
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v2.yaml@53cabff5231c0209c9a7a2b472f2fe90abc4ee23 # ratchet:navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v2.yaml@main
    needs: build
    with:
      cluster: dev-gcp
      id: "familie-ef-mikrofrontend-minside"
      url: ${{ needs.build.outputs.upload_url }}
      commitmsg: ${{ github.event.head_commit.message}}
    secrets: inherit
