name: "Build and deploy to dev and prod"

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    outputs:
      upload_url: ${{ steps.export-cdn-url.outputs.url }}
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-node@v4"
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"
      - name: "Install dependencies"
        run: "npm ci"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: "Build application"
        run: "npm run build"
      - name: cdn-upload
        id: cdn-upload
        uses: navikt/frontend/actions/cdn-upload/v1@main
        with:
          cdn-team-name: teamfamilie
          source: ./dist/
          destination: "familie-ef-mikrofrontend-minside"
      - name: export-cdn-url
        id: export-cdn-url
        run: |
          paths="${{ steps.cdn-upload.outputs.uploaded }}"
          cdn_js_path=$(echo $paths | cut -d',' -f1)
          echo "url=https://cdn.nav.no/$cdn_js_path" >> $GITHUB_OUTPUT
  manifest-update-dev:
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest.yaml@main
    needs: build
    with:
      cluster: dev-gcp
      id: "familie-ef-mikrofrontend-minside"
      url: ${{ needs.build.outputs.upload_url }}
    secrets: inherit

  manifest-update-prod:
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest.yaml@main
    needs: build
    with:
      cluster: prod-gcp
      id: "familie-ef-mikrofrontend-minside"
      url: ${{ needs.build.outputs.upload_url }}
    secrets: inherit
